maintainer = "Johnny Appleseed <john@apple.com>"
platform = "auto"
repository = "github.com/prod9/platform"
strategy = "timestamp"
excludes = ["*.docker", "*.local", ".dockerignore", ".git", ".github", ".gitignore", ".idea", ".svelte-kit", ".vscode", "build", "deploy", "dist", "node_modules", "platform.toml", "target"]

[modules]
  [modules.dockerfile]
    workdir = "."
    timeout = "1m0s"
    builder = "dockerfile"
